# Custom Language File for Launcher Customizer

[ejs.app]
title = "Le Dernier des Launchers"

[ejs.landing]
mediaGitHubURL = "https://github.com/pandaflip/LddLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/pandaflip/LddLauncher"
supportLink = "https://github.com/pandaflip/LddLauncher/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE DANS LE DERNIER DES MODPACKS"
welcomeDescription = "L'objectif ? Que ce soit le DERNIER des modpacks, ou qu'on le garde bien assez longtemps."
welcomeDescCTA = "Vous etes à quelques clics du dernier.."
